Remove snapd when there are no missing snaps

diff --git a/unsnap b/unsnap
--- a/unsnap
+++ b/unsnap
@@ -376,13 +376,19 @@ function run_scripts() {
         echo -e "${RED}ERROR:${NC} Failed to remove snaps" | tee -a "$LOGFILE"
         exit 14
     fi
-    # echo -e "${GREEN}INFO:${NC} Removing snapd daemon" | tee -a "$LOGFILE"
-    # if "$REMOVESNAPDSCRIPT"; then
-    #     echo -e "${GREEN}INFO:${NC} snapd removed" | tee -a "$LOGFILE"
-    # else
-    #     echo -e "${RED}ERROR:${NC} Failed to remove snapd" | tee -a "$LOGFILE"
-    #     exit 15
-    # fi
+
+    if [ -e "$MISSINGFLATPAK" ]; then
+        echo -e "${YELLOW}WARNING:${NC} the following snaps have no known alternative, will not remove snapd"
+        cat "$MISSINGFLATPAK"
+    else
+        echo -e "${GREEN}INFO:${NC} Removing snapd daemon" | tee -a "$LOGFILE"
+        if "$REMOVESNAPDSCRIPT"; then
+            echo -e "${GREEN}INFO:${NC} snapd removed" | tee -a "$LOGFILE"
+        else
+            echo -e "${RED}ERROR:${NC} Failed to remove snapd" | tee -a "$LOGFILE"
+            exit 15
+        fi
+    fi
 }
 
 function recommend_reboot() {
